world_trade_center_attacks = {
	"Known Fugitive": "Bin Laden",
	"Known Fugitive": "Mohamed Atta",
	"Known Fugitive Alt Name": "M Atta",
	"Known Fugitive Alt Name": "Mohamed A",
	"Known Fugitive": "Hani Hanjour",
	"Known Fugitive": "Wail Alshehri",
	"Known Fugitive": "Ziad Jarrah",
	"Known Fugitive": "Khalid Al-Mindhar",
	"Known Fugitive Alt Name": "Khalid A--Mihdhar",
	"Known Futitive Alt Name": "K Al-Mindhar",
	"Known Fugitive Alt Name": "Khalid A",
	"Known Fugitive": "Saeed Alghamdi",
	"Known Fugitive": "Nawaf Alhazmi",
	"Known Fugitive Alt Name": "Nawaf Al Hazmi",
	"Known Fugitive Alt Name": "N Alhazmi",
	"Known Fugitive Alt Name": "Nawaf A",
	"Known Fugitive Alt Name": "N Al Hazmi",
	"Known Fugitive": "Fayez (Abu Dhabi) Banihammad",
	"Known Fugitive": "Majed Moqed",
	"Known Fugitive": "Ahmed Alnami",
	"Known Fugitive": "Satam Al-Suqami",
	"Known Fugitive": "Waleed Alshehri",
	"Known Fugitive": "Mohand Alshehri",
	"Known Fugitive": "Abdul Alomari",
	"Known Fugitive": "Ahmed Alghamdi",
	"Known Fugitive": "Ahmed Alhaznawi",
	"Known Fugitive": "Hamza Alghamdi",
	"Known Fugitive Alt Name": "H Alghamdi",
	"Known Fugitive": "Salem Alhazmi",
	"Known Fugitive": "Marwan Alshehhi",
	"Known Fugitive Alt Name": "Marwan A"
	"Date of Criminal Activity": "September 11, 2001",
}